# Generated by Django 3.2.15 on 2022-08-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('descr_produto', models.CharField(blank=True, max_length=150)),
                ('preco_produto', models.FloatField()),
                ('imagem_produto', models.ImageField(upload_to='media/uploads/%Y/%m/%d')),
            ],
        ),
    ]
