# Generated by Django 3.2.15 on 2022-08-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220822_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished',
            new_name='published',
        ),
    ]
