# Generated by Django 3.2.15 on 2022-08-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
