# Generated by Django 3.2.15 on 2022-08-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(null=True, upload_to='media/uploads/% Y/% m/% d/'),
        ),
    ]
